version: '2'

networks:
  couchnet:

services:

  couchbase:
    image: couchbase:community-6.6.0
    networks:
      couchnet:
        aliases:
          - couchbase-backend
    restart: unless-stopped
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    volumes:
      - ./scripts/couchbase-setup.sh:/opt/couchbase/couchbase-setup.sh
    environment:
      COUCHBASE_USER: root
      COUCHBASE_DB: fileList
      COUCHBASE_PASSWORD: password
    entrypoint: "/bin/bash"
    command: ["/opt/couchbase/couchbase-setup.sh"]